package Methods_practice;

import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;

public class get_method2 
{
	public static void main(String[] args) throws InterruptedException
	{		
		ChromeDriver driver=new ChromeDriver();
		driver.manage().window().maximize();  		
		driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
		
//get window handle (to get window ID)= return(every time you get new window) ID generated by browser automatically and no two IDs are same
		System.out.println("The window ID is: "+ driver.getWindowHandle());

		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@id=\"app\"]/div[1]/div/div[1]/div/div[2]/div[3]/div[2]/p[2]/a")).click();
		
//get window handles (for multiple windows, when we need ID for every window we get after clicking on different links)		
		             //return us multiple window IDs
		Set<String> windowids=driver.getWindowHandles();  //set do not allow duplicate values
		for(String wid:windowids)
		{
			System.out.println("The window IDs are: "+ wid);
		}
		
		System.out.println("code executed successfully");
	    driver.close();
}}
